import Head from 'next/head'
import Link from 'next/link'
import Text from '../content.json'
import Header from '../components/Header/Header'
import Footer from '../components/Footer'
import Navigation from '../components/Navigation/index'
import {getUserInfo} from '../services/authentication/user'

export default function Home(props) {
  const {
    userName,
  } = props;
  return (
    <>
      <Head>
        <title>{Text.app.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header userName={userName}/>
      {/* pass role for different active tabs */}
      <Navigation role="admin"/>
      <main id='main'>
        <div role="heading" aria-level="2">
        {Text.app.title}
        </div>
        <nav>
          <Link href="/testPage">Test Page</Link>
        </nav>
      </main>
      <Footer />
    </>
  )
}

export async function getServerSideProps({ req }) {
  console.log(req);
  const userInfo = getUserInfo(req);
  return {
    props: {
      userName: `${userInfo.given_name} ${userInfo.family_name}`,
    },
  };
}

