import Head from 'next/head'
import Content from '../assets/content/content.json'
import Header from '../components/Header/index'
import Footer from '../components/Footer'
import Navigation from '../components/Navigation/index'
import {getUserInfo, getTokenInfo} from '../services/authentication/userAuthService'
import RequestLayout from '../components/RequestAccess/RequestLayout'
import { getUserName } from '../utils/helper'

export default function RequestAccess(props) {
  const {
    userName,
    userInfo,
  } = props;
  return (
    <>
      <Head>
        <title>{Content.requestAccess.pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header userName={userName}/>
      {/* pass role for different active tabs */}
      <Navigation role="admin" isUserRegistered={false}/>
      <main id="main">
        <RequestLayout userInfo={userInfo} />
      </main>
      <Footer />
    </>
  )
}

export async function getServerSideProps(ctx) {
  const authInfo = getTokenInfo(ctx)
  const userInfo = getUserInfo(authInfo);
  return {
    props: {
      userName: getUserName(userInfo),
      userInfo,
    },
  };
}
